### ISSUE TITLE
No BROKEN-LINK markup

### ISSUE THREAD

**Issue by retostauss** [turnermm/xtern#5]
When I check pages using the admin panel and click on a page link then the page opens in edit mode showing the broken links at the top of the page in yellow message banners. Unfortunately no BROKEN-LINK markup is added in the text.

I am using Release 2018-04-22b "Greebo", template [vector](https://www.dokuwiki.org/template:vector) and ckgedit (pages open by default in standard editor).

**Comment by turnermm** [comment]
In script.js, a line 17:

`  jQuery("#dokuwiki__content a" ).each (function( index ) { `

replace `"#dokuwiki__content a"`

 with    `"#bodyContent a"`

It's not perfect but it does get the broken links

**Comment by retostauss** [comment]
I tested the suggested fix and successfully tested. But: after going back to the old script.js it works too!

Yesterday I updated the xtern plugin. Was there any fix regarding this problem?

**Comment by turnermm** [comment]
No.  But perhaps your issue was related to this:  https://github.com/turnermm/xtern/issues/4, i.e. you hadn't run the admin app.  There was an update which added two new config options to set the div id or class if not the same as the default:   https://www.dokuwiki.org/plugin:xtern#configuration_options

**Comment by retostauss** [comment]
Seems to work without the patch
